SmartDiet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diet', include("diet.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from django.shortcuts import render
from django.views.static import serve

def custom_404(request, exception):
    return render(request, 'error.html', {
        "error_code": 404,
        "error_title": "Page Not Found",
        "error_message": "The page you requested does not exist."
    }, status=404)

handler404 = custom_404

urlpatterns = [
    path("diet/", include("core.urls")),
    path(
        "diet/collections/",
        decorator_include(login_required, "healthHub.urls")
    ),
    # path(
    #     "diet/progres/",
    #     decorator_include(login_required, "progress.urls")
    # ),
    path("diet/users/", include("users.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # Only for development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
 urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

core/urls.py
from django.urls import path , re_path

from . import views

urlpatterns = [
    path('progress/', views.logs, name='logs'),
    path('progress/assigned-plans/',views.assignedPlans,name="assignedPlans"),
    path('progress/avg-score/',views.avgScore,name="avgScore"),
    path('progress/day/',views.dayaData,name="dayData"),
    path("progress/period/", views.period_progress_view, name="period-progress"),
    
    path('progress/metric/', views.create_metric, name='create-metric'),
    path('progress/metric/<int:metric_id>/', views.update_metric, name='update-metric'),
    path('progress/metric/<int:metric_id>/value/', views.update_metric_value, name='update-metric-value'),
    path('progress/metric/<int:metric_id>/toggle/', views.toggle_metric_active, name='toggle-metric'),
    path('progress/metric/<int:metric_id>/delete/', views.delete_metric, name='delete-metric'),
    path('progress/metrics/inactive/', views.get_inactive_metrics, name='inactive-metrics'),
    path('progress/metrics/cleanup/', views.cleanup_unused_metrics, name='cleanup-metrics'),
    
    path('progress/feedback/', views.update_feedback, name='update-feedback'),
    path('dailyplan/set/', views.set_current_plan, name='set-current-plan'),

    re_path(r'^(?:(?P<slug>(login|register))/)?$', views.index, name='index'),
]

diet/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
import os
from django.conf import settings
from django.db import models
from datetime import date,timedelta

class User(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]

    ACTIVITY_LEVEL_CHOICES = [
        ('low', 'Low'),
        ('moderate', 'Moderate'),
        ('active', 'Active'),
        ('high', 'High'),
    ]


    SLEEP_QUALITY_CHOICES = [
        (1,'Deep'),
        (2,'Stable'),
        (3,'Mild'),
        (4,'Light'),
    ]   
    avatar_img = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    birth_date = models.DateField(default='2000-01-01')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='O')
    weight = models.DecimalField (default=50.00,max_digits=5, decimal_places=2)
    height = models.DecimalField (default=160.00,max_digits=5, decimal_places=2)  
    activity_level = models.CharField(max_length=10, choices=ACTIVITY_LEVEL_CHOICES, default='moderate')
    fluid_intake = models.DecimalField (default=2.0,max_digits=4, decimal_places=2)
    sleep_quality = models.IntegerField(choices=SLEEP_QUALITY_CHOICES, default=3)
    sleep_duration = models.DecimalField (default=7.0,max_digits=4, decimal_places=2) 
    friends = models.ManyToManyField("self", blank=True, symmetrical=False)

    def serialize(self):
        return {
           "avatar_img":self.avatar_img if self.image_exists() else '',
           "id": self.id,
            "username": self.username,
            "birth_date": self.birth_date.strftime("%Y-%m-%d"),
            "age":self.age(),
            "gender": dict(self.GENDER_CHOICES).get(self.gender, 'Unknown'),
            "weight": self.weight,
            "height": self.height,
            "activity_level": dict(self.ACTIVITY_LEVEL_CHOICES).get(self.activity_level, 'Unknown'),
            "fluid_intake": self.fluid_intake,
            "sleep_quality": dict(self.SLEEP_QUALITY_CHOICES).get(self.sleep_quality, 'Unknown'),
            "sleep_duration": self.sleep_duration,
            "email":self.email
        }
    def age(self):
        today = date.today()
        return today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
    
    def image_exists(self):
        # Check if the file exists
        full_path = os.path.join(settings.MEDIA_ROOT, self.avatar_img.name)
        return os.path.isfile(full_path)
    

    
class UserRemarks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="remarks")
    item = models.CharField(max_length=255)
    remark = models.CharField(max_length=255)
    class Meta:
        unique_together = ('user', 'item')
    def __str__(self):   
        return f'{self.item} {self.remark}'
        
class MedicalHistory(models.Model):
    RELATION_CHOICES = [
        (0, 'Own'),
        (1, 'Parent'),
        (2, 'sibling'),
        (3, 'Grand parent'),
        (4, 'Cousin'),
    ]  
    DEGREE_CHOICES = [
        (0, 'Severe'),
        (1, 'Averege'),
        (2, 'Light'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="medical_details")
    relation = models.IntegerField(choices=RELATION_CHOICES, default=0)
    issue = models.ForeignKey("MedicalIssue", on_delete=models.CASCADE, related_name="medical_issues")
    degree = models.IntegerField(choices=DEGREE_CHOICES, default=1)
    def __str__(self):   
        return f'{self.get_degree_display()} {self.issue.issue_name}'
    
    class Meta:
        unique_together = ('user', 'relation','issue','degree')        
    
class MedicalIssue(models.Model):
    issue_name = models.CharField(max_length=255,unique=True)  
    def __str__(self):   
        return self.issue_name 
   
class UserCreation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_%(class)s")
    title = models.CharField(max_length=255)
    remark = models.CharField(max_length=255,null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    last_modification = models.DateTimeField(auto_now=True)
    shared =  models.BooleanField(default=False)
    media = models.JSONField(default=list,null=True, blank=True)
    class Meta:
        unique_together = ('user', 'title')
        abstract = True
    def __str__(self):
        return f'{self.title}'

class Recipe(UserCreation):
    ingredients = models.JSONField(default=list)
    directions = models.TextField()
    category = models.CharField(max_length=255)
    prep_time =  models.DurationField(null=True,blank=True)
    serv = models.IntegerField(default=1)
    total_nurtients = models.JSONField(default=list)
    ingredients_nurtients = models.JSONField(default=list)

class Plan(UserCreation):
    plan_type = models.CharField(max_length=8, choices=[('full','Full'),('diet','Diet'),('exercies','Exercies')])
    duration = models.DurationField()
    goal = models.TextField()
     
class LinkedPlan(models.Model):
    full_plan = models.ForeignKey(
        Plan,
        on_delete=models.CASCADE,
         limit_choices_to={'plan_type': 'full'},
        related_name="full"
    )
    diet_plan =  models.ForeignKey(
        Plan,
        on_delete=models.SET_NULL,
        limit_choices_to={'plan_type': 'diet'},
        null=True,
        blank=True,
        related_name="diet"
    )
    exercies_plan = models.ForeignKey(
        Plan,
        on_delete=models.SET_NULL,
        limit_choices_to={'plan_type': 'exercies'},
        null=True,
        blank=True,
        related_name="exercies"
        )

class PlanDetail(models.Model):
    parent_section = models.ForeignKey('self', on_delete=models.CASCADE, related_name="sub_sections",null=True,blank=True )
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name="plan_details")
    section = models.CharField(max_length=255)
    detail = models.TextField(null=True,blank=True)
    order = models.IntegerField(default=1)
    def __str__(self):
        return f'{self.plan}_{self.section}'

class Collection(models.Model):
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, related_name="group_folders",null=True,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_groups")
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    class Meta:
        unique_together = ('user', 'title')
    def __str__(self):
        return self.title
class UserFav(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="fav_%(class)s")
    favourite = models.BooleanField(default=False)
    groups =  models.ManyToManyField(Collection, related_name="group_%(class)s")
    class Meta:
        abstract = True

class UserRecipe(UserFav):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="user_recipes")

class UserPlan(UserFav):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name="user_plans")

class UserLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="history")
    date = models.DateField()
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name="user_history", null=True, blank=True)
    score = models.IntegerField(default=0,validators=[ MinValueValidator(0),MaxValueValidator(100)])
    feedback = models.TextField(null=True, blank=True)
    def __str__(self):
        return f'user_{self.user.id}_{self.date}_{self.plan}'

    @staticmethod
    def get_current_plan(user,type):
        today = date.today()
        last_type_log = UserLog.objects.filter(user=user,plan__plan_type=type).order_by('-date').first()
        last_log = UserLog.objects.filter(user=user,date__lte=today).order_by('-date').first()
        if last_log.plan.plan_type != 'full':
            last_log  =last_type_log
        if not last_log:
            return None
        if last_log.date == today:
            return last_log.plan
        elif last_log.date < today:
            UserLog.log_missing_logs(last_log.date,today,last_log)
            return last_log.plan
        else:
            today_log = UserLog.objects.filter(user=user,plan__plan_type__in=[type, "full"],date=today).first()
            if not today_log:
                today_log = UserLog.objects.filter(user=user,plan__plan_type__in=[type, "full"],date__lt=today).order_by('-date').first()
                UserLog.log_missing_logs(today_log.date,today,last_log)
            return today_log.plan    
               


    @staticmethod
    def log_missing_logs(date,today,log):
        current_date = date + timedelta(days=1)
        while current_date <= today:
            UserLog.set_plan(log.user, log.plan, current_date)
            current_date += timedelta(days=1)
   
    @staticmethod
    def set_plan(user, plan, start_date,fill_duration=False, replace=False):
        end_date = start_date + plan.duration if fill_duration else start_date + timedelta(days=1)
        while start_date < end_date:
            if plan.plan_type != 'full':
                UserLog.add_plan(user, plan, start_date, replace)
            else:
                UserLog.add_full_plan(user, plan, start_date, replace)               
            start_date += timedelta(days=1)


    @staticmethod
    def add_full_plan(user, plan, start_date, replace=False):
        existing_logs = UserLog.objects.filter(user=user, date=start_date)
        if len(existing_logs) == 0:
            new_log = UserLog(user=user, date=start_date,plan=plan)
            new_log.save()
        elif len(existing_logs) > 0 and (replace or start_date !=  date.today()):
            linked_plan = LinkedPlan.objects.get(full_plan=plan)
            feedback = ''
            score = 0

templates/components/profile/header.html
{% load static %}

<div id="profile-header">
  <div class="img_container">
    <div id="avatar">
      <template x-if="!home">
        <input
          x-ref="imgUpload"
          type="file"
          name="avatar_img"
          accept="image/*"
          class="d-none"
          id="id_avatar_img"
          @change="profile.updateAvatarImage()"
        />
      </template>
      <img
        x-ref="avataImg"
        alt="{{user.username}} avatar image"
        src="{{user.avatar_img}}"
        :src="user.avatar_img"
        data-fallback="{% static 'assets/profile.jpg' %}"
        onerror="this.src=this.dataset.fallback;"
        @dblclick="!$data.home ? $refs.imgUpload.click():''"
      />
    </div>
  </div>
  <h1
    x-text="user.username"
    x-show="!editMode"
    @dblclick="
    if (!$data.home) {
      editMode = true;
      $data.orgValue = $data.user.username;
      $refs.nameInput.focus();
    }
  "
  >
    {{user.username|capfirst }}
  </h1>
  <template x-if="!home">
    <h1 x-show="editMode">
      <input
        x-model="user.username"
        class="form-control"
        x-ref="nameInput"
        @keydown.enter.prevent="$el.blur()"
        @keydown="$el.classList.remove('invalid')"
        @blur="profile.updateUserName()"
      />
    </h1>
  </template>
</div>

templates/components/profile/lifeStyle.html
<div class="info-card" >
  <div class="section-name">
    <p>Lifestyle Info</p>
    <button type="button" @click="active='lifeStyle'"
      :style="(!full && active === 'lifeStyle')
    ? 'background-color: rgb(var(--highlight-rgb))'
    : ''"
></button>
  </div>
  <div class="section-content" x-show="full || active=='lifeStyle'">
    <div class="d-flex flex-column flex-lg-row justify-content-between mb-1">
      <div style="width:45%;">
        <b>Activity Level:</b>
        <select x-model="user.activity_level" class="form-control" @change="profile.updateUserData($event.target,'activity_level')">
          {% for key, value in ACTIVITY_LEVEL_CHOICES %}
          <option value="{{ key }}" :selected="user.activity_level === '{{ key }}'">{{ value }}</option>
          {% endfor %}
        </select>
      </div>
      <div style="width:45%;">
        <b>Fluid Intake:</b>
        <span class="d-flex align-items-center">
            <input type="number" x-model.number="user.fluid_intake" class="form-control" @change="profile.updateUserData($event.target,'fluid_intake')">
             <b>L</b>
        </span>
      </div>
    </div>

    <b>Sleep Data:</b>
    <div class="d-flex flex-column flex-lg-row justify-content-between mb-1">
      <div style="width:45%;">
        <b>Quality:</b>
        <select x-model="user.sleep_quality" class="form-control" @change="profile.updateUserData($event.target,'sleep_quality')">
          {% for key, value in SLEEP_QUALITY_CHOICES %}
          <option value="{{ key }}" :selected="user.sleep_quality === '{{ key }}'" >{{ value }}</option>
          {% endfor %}
        </select>
      </div>
      <div style="width:45%;">
        <b>Duration:</b>
        <span class="d-flex align-items-center">
            <input type="number" x-model.number="user.sleep_duration" class="form-control" @change="profile.updateUserData($event.target,'sleep_duration')">
            <b>H</b>

        </span>
      </div>
    </div>
    <hr>
  </div>
</div>

templates/components/profile/personalInfo.html
<div class="info-card">
  <div class="section-name">
    <p>Personal Info</p>
    <button
      type="button"
      @click="active='personalInfo'"
      :style="(!full && active === 'personalInfo')
    ? 'background-color: rgb(var(--highlight-rgb))'
    : ''"
    ></button>
  </div>
  <div class="section-content" x-show="full || active=='personalInfo'">
    <p><b>Email:</b><span x-text="user.email">{{user.email}}</span></p>
    <div class="d-flex flex-column flex-lg-row justify-content-between">
      <p style="width: 30%">
        <b>Age: </b><span x-text="user.age">{{user.age}}</span>
      </p>
      <div class="d-flex" style="width: 65%">
        <b style="width: 140px">Birth Date:</b>
        <input
        @change="profile.updateUserData($event.target,'birth_date')"
          type="date"
          name="birth_date"
          value="{{user.birth_date}}"
          x-model="user.birth_date"
          class="form-control"
          style="width: 70%"
        />
      </div>
    </div>
    <b>Gender:</b>
    <div class="d-flex gap-5 mb-3 justify-content-around">
      <label>
        <input type="radio" value="M" x-model="user.gender" @change="profile.updateUserData($event.target,'gender')"/> Male
      </label>
      <label>
        <input type="radio" value="F" x-model="user.gender" @change="profile.updateUserData($event.target,'gender')"/> Female
      </label>
      <label>
        <input type="radio" value="O" x-model="user.gender" @change="profile.updateUserData($event.target,'gender')"/> Other
      </label>
    </div>
    <div class="d-flex flex-column flex-lg-row justify-content-between">
      <div style="width: 45%">
        <b>Weight :</b>
        <span class="d-flex">
          <input
            @change="profile.updateUserData($event.target,'weight')"
            type="number"
            class="form-control"
            x-model.number="user.weight"
          />
          <b>kg</b>
        </span>
      </div>
      <div style="width: 45%">
        <b>height: </b>
        <span class="d-flex">
          <input
          @change="profile.updateUserData($event.target,'height')"
            type="number"
            class="form-control"
            x-model.number="user.height"
          />
          <b>cm</b>
        </span>
      </div>
    </div>
    <hr />
  </div>
</div>

templates/components/profile/restrictions.html
<div class="info-card move" x-show="full || active=='restrictions'">
  <div class="section-name" x-show="full">
    <p>User Restrictions</p>
    <button type="button"></button>
  </div>

  <div class="section-content">
    <p style="font-size: 14px">
      This section includes any extra info to take note of while making a plan
      like preferences or restrictions.
    </p>

    <div
      class="content form-control p-1"
      style="width: 100%; overflow-x: auto; background-color: transparent"
    >
      <table
        x-ref="restrictionsTable"
        class="table table-borderless table-sm mb-0"
        style="background-color: transparent"
      >
        <thead>
          <tr>
            <th style="width: 30%">Name</th>
            <th style="width: 50%">Remark</th>
            <th style="width: 20%">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for type_key, type_label in RESTRICTIONS_TYPE_CHOICES %}
          <!-- Type header row -->
          <tr class="bg-secondary text-white">
            <td colspan="3">
              <div
                class="d-flex justify-content-between align-items-center w-100 px-2"
                @click="activeType='{{type_label}}'"
              >
                <span class="fw-bold">{{ type_label }}</span>
                <button
                  type="button"
                  class="btn btn-sm btn-primary"
                  @click="profile.addRestriction('{{ type_key }}')"
                >
                  + Add
                </button>
              </div>
            </td>
          </tr>

          <!-- Rows for this type -->
          <template
            x-for="(r, index) in user.restrictions.filter(res => res.type === '{{ type_key }}')"
            :key="r.id"
          >
            <tr
              style="
                background-color: transparent;
                border-bottom: 1px solid rgba(0, 0, 1, 0.1);
              "
              x-show="!collapse || activeType == '{{type_label}}'"
            >
              <td>
                <template x-if="r.type === 'medical'">
                  <select
                    class="form-control form-control-sm bg-transparent border-0"
                    x-init="$nextTick(() => profile?.registerRef(r.id, 'name', $el))"
                    @destroy="profile?.unregisterRef(r.id, 'name')"
                    x-model="r.medicalId"
                    @change="profile.updateRestrictions(r.id,r.type)"
                  >
                    <option value="">Select medical restriction</option>
                    {% for m in medicalRestrictions %}
                    <option value="{{m.id}}" title="{{m.description_en}}">
                      {{m.name_en}}
                    </option>
                    {% endfor %}
                  </select>
                </template>
                <!-- NON-MEDICAL: FREE TEXT -->
                <template x-if="r.type !== 'medical'">
                  <input
                    type="text"
                    @blur="profile.updateRestrictions(r.id,r.type)"
                    class="form-control form-control-sm bg-transparent border-0"
                    x-init="$nextTick(() => profile?.registerRef(r.id, 'name', $el))"
                    @destroy="profile?.unregisterRef(r.id, 'name')"
                    x-model="r.name"
                    placeholder="Enter name"
                  />
                </template>
              </td>
              <td>
                <input
                  type="text"
                  class="form-control form-control-sm bg-transparent border-0"
                  x-init="$nextTick(() => profile?.registerRef(r.id, 'remark', $el))"
                  @destroy="profile?.unregisterRef(r.id, 'remark')"
                  @blur="profile.updateRestrictions(r.id,r.type)"
                  x-model="r.remark"
                  placeholder="Enter remark"
                />
              </td>
              <td class="d-flex justify-content-center align-items-center">
                <button
                  type="button"
                  class="btn btn-sm btn-danger"
                  @click="profile.removeRestriction(r.id)"
                >
                  <i class="fas fa-trash"></i>
                </button>
              </td>
            </tr>
          </template>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <hr />
  </div>
</div>